#!/bin/bash

pdp11-aout-gcc \
-c \
-m45 \
-mfpu \
-Os \
-I /home/engdahl/PDP-11/include \
-Wall \
-Wextra \
-std=gnu17  \
$2 $3 $4 $5 $6 $7 $8 $9 $1 -o $1.o

pdp11-aout-objdump -d $1.o | python3 hex2oct.py
